const express=require('express');const http=require('http');const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static('public'));
const rooms=new Map();const colors=['red','blue','green','yellow'];
function makeDeck(){const d=[];for(const color of colors){for(let n=1;n<=9;n++){const count=(n===1||n===9)?1:2;for(let i=0;i<count;i++)d.push({type:'number',color,value:n,id:crypto.randomUUID()})}}const add=(type,count)=>{for(let i=0;i<count;i++)d.push({type,id:crypto.randomUUID()})};add('switch',4);add('skip',4);add('draw2',4);add('wild',4);add('mirror',4);add('boom',2);add('steal',2);return d.sort(()=>Math.random()-.5)}
function roomState(r){return {players:r.players.map(p=>({id:p.id,name:p.name,count:p.hand.length})),top:r.discard.at(-1),color:r.color,turn:r.players[r.turn]?.id,started:r.started,winner:r.winner||null,drawCount:r.drawCount||0}}
function broadcast(code){const r=rooms.get(code);if(r)io.to(code).emit('state',roomState(r))}
function draw(r,n){for(let i=0;i<n;i++){if(!r.deck.length){const top=r.discard.pop();r.deck=r.discard.sort(()=>Math.random()-.5);r.discard=[top]}const p=r.players[r.turn];if(r.deck.length)p.hand.push(r.deck.pop())}}
function canPlay(card,r){const top=r.discard.at(-1);if(card.type==='wild'||card.type==='switch'||card.type==='skip'||card.type==='draw2'||card.type==='mirror'||card.type==='boom'||card.type==='steal')return true;return card.color===r.color||card.value===top.value}
function next(r,steps=1){r.turn=(r.turn+steps)%r.players.length}
function start(r){r.deck=makeDeck();r.discard=[];r.players.forEach(p=>p.hand=[]);for(let i=0;i<7;i++)r.players.forEach(p=>p.hand.push(r.deck.pop()));let first=r.deck.pop();while(first.type!=='number')r.deck.unshift(first),first=r.deck.pop();r.discard.push(first);r.color=first.color;r.turn=0;r.started=true;r.winner=null;r.drawCount=0}
io.on('connection',s=>{s.on('create',({name},cb)=>{let code=Math.random().toString(36).slice(2,6).toUpperCase();while(rooms.has(code))code=Math.random().toString(36).slice(2,6).toUpperCase();rooms.set(code,{players:[{id:s.id,name:(name||'Speler').slice(0,18),hand:[]}],started:false,deck:[],discard:[],turn:0,color:null});s.join(code);s.data.code=code;cb({code});broadcast(code)});s.on('join',({code,name},cb)=>{code=String(code||'').toUpperCase();const r=rooms.get(code);if(!r||r.started||r.players.length>=6)return cb({error:'Room bestaat niet, is al gestart of zit vol.'});r.players.push({id:s.id,name:(name||'Speler').slice(0,18),hand:[]});s.join(code);s.data.code=code;cb({code});broadcast(code)});s.on('start',()=>{const r=rooms.get(s.data.code);if(r&&r.players[0].id===s.id&&r.players.length>=2){start(r);broadcast(s.data.code);r.players.forEach(p=>io.to(p.id).emit('hand',p.hand))}});s.on('play',({index,wildColor})=>{const code=s.data.code,r=rooms.get(code);if(!r||!r.started||r.winner||r.players[r.turn].id!==s.id)return;const p=r.players[r.turn],card=p.hand[index];if(!card||!canPlay(card,r))return; p.hand.splice(index,1);r.discard.push(card);if(card.type==='wild'){r.color=colors.includes(wildColor)?wildColor:r.color}else if(card.color)r.color=card.color;
if(card.type==='switch'){const hands=r.players.map(x=>x.hand);for(let i=0;i<r.players.length;i++)r.players[i].hand=hands[(i+1)%r.players.length]}
if(card.type==='skip')next(r,2);else if(card.type==='draw2'){r.drawCount=(r.drawCount||0)+2;next(r);for(let i=0;i<r.drawCount;i++)draw(r,1);r.drawCount=0;next(r)}else if(card.type==='mirror'){next(r);const need=r.discard[r.discard.length-2];const q=r.players[r.turn];if(!q.hand.some(c=>c.type==='number'&&need&&c.value===need.value)){draw(r,2);next(r)}}else if(card.type==='boom'){r.players.forEach(x=>{if(x.hand.length){const i=Math.floor(Math.random()*x.hand.length);x.boom=x.hand.splice(i,1)[0]}});r.players.forEach(x=>{const arr=r.players.filter(y=>y.boom).map(y=>y.boom);if(arr.length){x.hand.push(arr[Math.floor(Math.random()*arr.length)]);delete x.boom}});next(r)}else if(card.type==='steal'){next(r);const target=r.players[r.turn];if(target.hand.length){const i=Math.floor(Math.random()*target.hand.length);p.hand.push(target.hand.splice(i,1)[0])}next(r)}else next(r);if(p.hand.length===0)r.winner=p.id;else if(r.players.length)broadcast(code);r.players.forEach(x=>io.to(x.id).emit('hand',x.hand))});s.on('draw',()=>{const r=rooms.get(s.data.code);if(!r||!r.started||r.winner||r.players[r.turn].id!==s.id)return;draw(r,1);next(r);broadcast(s.data.code);r.players.forEach(x=>io.to(x.id).emit('hand',x.hand))});s.on('disconnect',()=>{const code=s.data.code,r=rooms.get(code);if(!r)return;r.players=r.players.filter(p=>p.id!==s.id);if(!r.players.length)rooms.delete(code);else{if(r.turn>=r.players.length)r.turn=0;broadcast(code)}})});
server.listen(process.env.PORT||3000,()=>console.log('SWITCH draait op http://localhost:'+(process.env.PORT||3000)));
